---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-cluster-test
  namespace: argocd
spec:
  destination:
    namespace: redis-cluster-test-ns
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://github.com/shubham-cmyk/argocd-redis.git
      path: kbm.test/redis-cluster-test.yaml
      targetRevision: redis-cluster-test
  project: default
  syncPolicy:
    automated:
    syncOptions: [CreateNamespace=true, ApplyOutOfSyncOnly=true]
